In [1]:
import os
import pandas as pd
os.listdir()

['.ipynb_checkpoints',
 '.~clean_actor_attributes.ipynb',
 'clean_actor_attributes.ipynb',
 'clean_movie_attributes.ipynb',
 'name_basics_cleaned.tsv',
 'name_basics_cleaned_no_index.tsv',
 'name_basics_cleaned_with_index.tsv',
 'name_basics_full.tsv',
 'title_akas_full.tsv',
 'title_basics_cleaned.tsv',
 'title_basics_cleaned2.tsv',
 'title_basics_full.tsv',
 'title_episode_full.tsv',
 'title_principals_full.tsv',
 'title_ratings_full.tsv',
 'Untitled.ipynb']

In [2]:
df = pd.read_csv("name_basics_full.tsv", sep = '\t')

In [3]:
df.head()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0043044,tt0050419,tt0053137,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0038355,tt0037382,tt0071877"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,producer","tt0054452,tt0059956,tt0049189,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,writer,soundtrack","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050976,tt0083922,tt0069467,tt0050986"

In [4]:
print(len(df))

9732109

In [5]:
df.head(20)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0043044,tt0050419,tt0053137,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0038355,tt0037382,tt0071877"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,producer","tt0054452,tt0059956,tt0049189,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,writer,soundtrack","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050976,tt0083922,tt0069467,tt0050986"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0038787,tt0077711,tt0036855,tt0038109"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0034583,tt0033870,tt0043265,tt0037382"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0068646,tt0044081"
8,nm0000009,Richard Burton,1925,1984,"actor,producer,soundtrack","tt0061184,tt0059749,tt0057877,tt0087803"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0035575,tt0029870,tt0042041"
10,nm0000011,Gary Cooper,1901,1961,"actor,soundtrack,producer","tt0027996,tt0044706,tt0035896,tt0034167"
11,nm0000012,Bette Davis,1908,1989,"actress,soundtrack,make_up_department","tt0056687,tt0042192,tt0035140,tt0031210"
12,nm0000013,Doris Day,1922,2019,"soundtrack,actress,producer","tt0053172,tt0060463,tt0055100,tt0048317"
13,nm0000014,Olivia de Havilland,1916,\N,"actress,soundtrack","tt0041452,tt0040806,tt0031381,tt0029843"
14,nm0000015,James Dean,1931,1955,"actor,miscellaneous","tt0048545,tt0049261,tt0044245,tt0048028"
15,nm0000016,Georges Delerue,1925,1992,"composer,soundtrack,music_department","tt0057345,tt0091763,tt0069946,tt0096320"
16,nm0000017,Marlene Dietrich,1901,1992,"soundtrack,actress,music_department","tt0051201,tt0052311,tt0055031,tt0021156"
17,nm0000018,Kirk Douglas,1916,\N,"actor,producer,soundtrack","tt0080736,tt0052365,tt0054331,tt0043338"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0053779,tt0071129,tt0056801,tt0047528"
19,nm0000020,Henry Fonda,1905,1982,"actor,producer,soundtrack","tt0032551,tt0050083,tt0064116,tt0082846"

In [6]:
df = df.replace('\\N', "Unavailable")

In [7]:
df.head(20)

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0043044,tt0050419,tt0053137,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0038355,tt0037382,tt0071877"
2,nm0000003,Brigitte Bardot,1934,Unavailable,"actress,soundtrack,producer","tt0054452,tt0059956,tt0049189,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,writer,soundtrack","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050976,tt0083922,tt0069467,tt0050986"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0038787,tt0077711,tt0036855,tt0038109"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0034583,tt0033870,tt0043265,tt0037382"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0068646,tt0044081"
8,nm0000009,Richard Burton,1925,1984,"actor,producer,soundtrack","tt0061184,tt0059749,tt0057877,tt0087803"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0035575,tt0029870,tt0042041"
10,nm0000011,Gary Cooper,1901,1961,"actor,soundtrack,producer","tt0027996,tt0044706,tt0035896,tt0034167"
11,nm0000012,Bette Davis,1908,1989,"actress,soundtrack,make_up_department","tt0056687,tt0042192,tt0035140,tt0031210"
12,nm0000013,Doris Day,1922,2019,"soundtrack,actress,producer","tt0053172,tt0060463,tt0055100,tt0048317"
13,nm0000014,Olivia de Havilland,1916,Unavailable,"actress,soundtrack","tt0041452,tt0040806,tt0031381,tt0029843"
14,nm0000015,James Dean,1931,1955,"actor,miscellaneous","tt0048545,tt0049261,tt0044245,tt0048028"
15,nm0000016,Georges Delerue,1925,1992,"composer,soundtrack,music_department","tt0057345,tt0091763,tt0069946,tt0096320"
16,nm0000017,Marlene Dietrich,1901,1992,"soundtrack,actress,music_department","tt0051201,tt0052311,tt0055031,tt0021156"
17,nm0000018,Kirk Douglas,1916,Unavailable,"actor,producer,soundtrack","tt0080736,tt0052365,tt0054331,tt0043338"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0053779,tt0071129,tt0056801,tt0047528"
19,nm0000020,Henry Fonda,1905,1982,"actor,producer,soundtrack","tt0032551,tt0050083,tt0064116,tt0082846"

In [8]:
indexToDrop = df[ df['birthYear'] == "Unavailable"].index
df.drop(indexToDrop, inplace = True)

In [9]:
len(df)

492086

In [10]:
df.tail()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
9731832,nm9993426,Nick 'Duffy' Fudge,1989,2018,NaN,Unavailable
9731837,nm9993432,Albert Minns,1920,1985,NaN,tt0189339
9731838,nm9993434,Richard Blackmarr,1929,2013,NaN,tt0189339
9731839,nm9993435,William Riva,1919,1999,set_decorator,tt0189339
9731840,nm9993436,Frank J. Gaily,1915,2008,sound_department,tt0189339

In [12]:
df.to_csv("name_basics_cleaned_with_index_and_label.tsv", sep = '\t', index = False)

In [59]:
df.to_csv("name_basics_cleaned_no_index.tsv", sep = '|', index = False)

In [39]:
df.tail()

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
9731832,nm9993426,Nick 'Duffy' Fudge,1989,2018,NaN,Unavailable
9731837,nm9993432,Albert Minns,1920,1985,NaN,tt0189339
9731838,nm9993434,Richard Blackmarr,1929,2013,NaN,tt0189339
9731839,nm9993435,William Riva,1919,1999,set_decorator,tt0189339
9731840,nm9993436,Frank J. Gaily,1915,2008,sound_department,tt0189339

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0043044,tt0050419,tt0053137,tt0072308"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0117057,tt0038355,tt0037382,tt0071877"
2,nm0000003,Brigitte Bardot,1934,Unavailable,"actress,soundtrack,producer","tt0054452,tt0059956,tt0049189,tt0057345"
3,nm0000004,John Belushi,1949,1982,"actor,writer,soundtrack","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050976,tt0083922,tt0069467,tt0050986"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0038787,tt0077711,tt0036855,tt0038109"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0034583,tt0033870,tt0043265,tt0037382"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0078788,tt0070849,tt0068646,tt0044081"
8,nm0000009,Richard Burton,1925,1984,"actor,producer,soundtrack","tt0061184,tt0059749,tt0057877,tt0087803"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0031867,tt0035575,tt0029870,tt0042041"
10,nm0000011,Gary Cooper,1901,1961,"actor,soundtrack,producer","tt0027996,tt0044706,tt0035896,tt0034167"
11,nm0000012,Bette Davis,1908,1989,"actress,soundtrack,make_up_department","tt0056687,tt0042192,tt0035140,tt0031210"
12,nm0000013,Doris Day,1922,2019,"soundtrack,actress,producer","tt0053172,tt0060463,tt0055100,tt0048317"
13,nm0000014,Olivia de Havilland,1916,Unavailable,"actress,soundtrack","tt0041452,tt0040806,tt0031381,tt0029843"
14,nm0000015,James Dean,1931,1955,"actor,miscellaneous","tt0048545,tt0049261,tt0044245,tt0048028"
15,nm0000016,Georges Delerue,1925,1992,"composer,soundtrack,music_department","tt0057345,tt0091763,tt0069946,tt0096320"
16,nm0000017,Marlene Dietrich,1901,1992,"soundtrack,actress,music_department","tt0051201,tt0052311,tt0055031,tt0021156"
17,nm0000018,Kirk Douglas,1916,Unavailable,"actor,producer,soundtrack","tt0080736,tt0052365,tt0054331,tt0043338"
18,nm0000019,Federico Fellini,1920,1993,"writer,director,assistant_director","tt0053779,tt0071129,tt0056801,tt0047528"
19,nm0000020,Henry Fonda,1905,1982,"actor,producer,soundtrack","tt0032551,tt0050083,tt0064116,tt0082846"
20,nm0000021,Joan Fontaine,1917,2013,"actress,soundtrack,producer","tt0039504,tt0032976,tt0034248,tt0040536"
21,nm0000022,Clark Gable,1901,1960,"actor,soundtrack,producer","tt0031381,tt0025316,tt0026752,tt0052278"
22,nm0000023,Judy Garland,1922,1969,"soundtrack,actress","tt0037059,tt0055031,tt0047522,tt0032138"
23,nm0000024,John Gielgud,1904,2000,"actor,writer,director","tt0071877,tt0082031,tt0117631,tt0045943"
24,nm0000025,Jerry Goldsmith,1929,2004,"music_department,soundtrack,composer","tt0119488,tt0100802,tt0112715,tt0117731"
25,nm0000026,Cary Grant,1904,1986,"actor,soundtrack,producer","tt0053125,tt0032599,tt0056923,tt0048728"
26,nm0000027,Alec Guinness,1914,2000,"actor,soundtrack,writer","tt0076759,tt0050212,tt0041546,tt0051739"
27,nm0000028,Rita Hayworth,1918,1987,"actress,soundtrack,producer","tt0038559,tt0040552,tt0040525,tt0036723"
28,nm0000029,Margaux Hemingway,1954,1996,"actress,miscellaneous","tt0074802,tt0077800,tt0102122,tt0110138"
29,nm0000030,Audrey Hepburn,1929,1993,"actress,soundtrack","tt0046250,tt0056923,tt0054698,tt0058385"
...,...,...,...,...,...,...
9725650,nm9986479,Ryan Nobbs,1986,Unavailable,NaN,Unavailable
9725916,nm9986770,Kati Gold,1996,Unavailable,actress,Unavailable
9726176,nm9987048,Michael Maltby,1942,Unavailable,"director,producer",Unavailable
9726363,nm9987249,Sasa Krnetic,1983,2018,NaN,Unavailable
9726621,nm9987517,Praewa Suthamphong,2001,Unavailable,actress,tt8730152
9726625,nm9987521,Patchanan Jiajirachote,1997,Unavailable,NaN,"tt8730152,tt8733014"
9726696,nm9987595,Megan Miskiewicz,1985,Unavailable,actor,tt6139810
9726762,nm9987668,Andrey Belozerov,1972,Unavailable,actor,tt6226710
9727812,nm9988760,Lingesh.m,1992,Unavailable,visual_effects,"tt3829266,tt6565702,tt5884052,tt1477834"
9727914,nm9988866,Douglas Preiser,1953,Unavailable,NaN,Unavailable
9728190,nm9989149,Zsanna Lehóczki,1999,Unavailable,actress,Unavailable
9728199,nm9989158,Attila Jankó,1999,Unavailable,actor,tt8723836
9728842,nm9989841,Din Fan,1990,Unavailable,actor,"tt10188826,tt5953804"
9728854,nm9989854,Layla Louise,1990,Unavailable,"actress,stunts","tt9335490,tt8894778,tt9898328,tt9910102"
9728991,nm9990008,Olavo Bilac,1865,1918,writer,tt8735938
9729159,nm9990184,Crystal Loverro,1995,Unavailable,"actress,assistant_director,producer","tt8736224,tt10153878,tt9224020,tt11058072"
9729251,nm9990278,Aziel Tan,2002,Unavailable,actor,Unavailable
9730876,nm9992306,Janny Schulte,1980,Unavailable,"writer,costume_department,miscellaneous","tt8741168,tt8741866"
9730914,nm9992344,Sam Shock,1987,Unavailable,actor,"tt9346524,tt7418356,tt4229630,tt8567392"
9731015,nm9992481,Nicholas Mata,1988,Unavailable,"producer,writer","tt9635200,tt8741974"
9731169,nm9992650,Pardeep Singh Sooch,1987,Unavailable,actor,"tt1094229,tt4878326"
9731277,nm9992812,Daisy,1994,Unavailable,actress,tt8281190
9731387,nm9992946,Christoph Blaschke,1993,Unavailable,"assistant_director,camera_department,director","tt8742618,tt9738336,tt8281532,tt10172548"
9731411,nm9992971,Shamica Anderson,1988,Unavailable,"sound_department,writer,editor",Unavailable
9731789,nm9993379,Fanny Hozleiter,1988,Unavailable,"director,actress,writer",tt8743182
9731832,nm9993426,Nick 'Duffy' Fudge,1989,2018,NaN,Unavailable
9731837,nm9993432,Albert Minns,1920,1985,NaN,tt0189339
9731838,nm9993434,Richard Blackmarr,1929,2013,NaN,tt0189339
9731839,nm9993435,William Riva,1919,1999,set_decorator,tt0189339
9731840,nm9993436,Frank J. Gaily,1915,2008,sound_department,tt0189339